---
title: "hexmas"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{hexmas}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## About this app

This app has been built by [Colin Fay](https://twitter.com/_ColinFay), as an illustration of an app built using the `{golem}` Framework. It's a general User Interface for the `{hexSticker}` package.

Colin works at [ThinkR](https://rtask.thinkr.fr), a french company focused on R engineering, creator and maintainer of the `{golem}` package.

### Find ThinkR on :

+ [The web](https://rtask.thinkr.fr)
+ [Twitter](https://twitter.com/ThinkR_FR)
+ [GitHub](https://github.com/ThinkR-open)

## Tech used in this app 

+ The [`{golem}`](https://github.com/ThinkR-open/golem) Framework was used to build the Shiny App backend. 

+ The whole app is powererd by [`{shiny}`](https://github.com/rstudio/shiny).

+ Sticker is generated by [`{hexSticker}`](https://github.com/GuangchuangYu/hexSticker)

+ Image modification is done with the [`{magick}`](https://github.com/ropensci/magick) package. 

+ The app links to MongoDB using [`{mogolite}`](https://github.com/jeroen/mongolite).

+ Application guided tour was created using [`{cicerone}`](https://github.com/JohnCoene/cicerone).

To see the full list of packages used in the app, refer to the [DESCRIPTION](https://github.com/ColinFay/hexmake/blob/master/DESCRIPTION) file.

+ The app was deployed on [RStudio Connect](https://rstudio.com/products/connect/)

Browse the full source code at https://github.com/ColinFay/hexmake

## How to use this App 

### Live mode and Manual mode

The live preview mode allows you to automatically regenerate the hex every time you change one input.

In some rare cases this might make the app a little bit slower, especially if you're playing around with colors, hence the possibility to change this to manual mode. In manual mode, you'll need to click on the render button to see the changes in your image.

### Manage name

This part handles the Name layer. 

### Manage image

Here, you can upload an image from your computer to be used as an image for your sticker. 

Parameters allow you to play with the position and size of the image.

The "Modify" window allows you to perform basic image manipulation using the [`{magick}`](https://github.com/ropensci/magick) package. 

### Manage Hexagon

Change the borders and fill of the hex stickers.

### Manage Spotlight

Here you can parametrize a spotlight on your sticker. 

### Manage URL

Here you can parametrize the url printed on the sticker.